"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """\
[╭─ ](243)$env_var$all\
[╰─](243)$character"""


[directory]
format = "[$path]($style) "
read_only = " 󰌾"
truncation_length = 3
truncation_symbol = "…/"

[env_var.STARSHIP_DISTRO]
format = '[$env_value](249)  '
variable = "STARSHIP_DISTRO"
disabled = false

[container]
disabled = true

[aws]
disabled = true

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "